### ISSUE TITLE
Hide/Show child nodes of a branch

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#105]
**Proposed feature**
Currently it is not possible to hide branches of trees which makes big mind maps complicated to read. Therefore, a possibility to hide branches would be nice.

- [ ] Add a new toolbar icon to hide a branch, search for a good icon which changes depending on hidden/visible state.
- [ ] It should set the node state to invisible
- [ ] Invisible nodes shouldn't be shown in the map
- [ ] Check node data model if a new field is needed
- [ ] It might be helpful to show a small symbol next to a node if the branch is set to invisible. Otherwise one might overlook that.

**Comment by warnat** [comment]
this would be awesome and enhance the whole picture a lot

**Comment by JannikStreek** [comment]
> this would be awesome and enhance the whole picture a lot

Hi @warnat, do you have a preference / thoughts on how to handle the image export? Should hidden nodes be visible on exported images? Or should they remain hidden? 🤔

**Comment by warnat** [comment]
I think, just leave them collapsed. Sometimes someone might need only a part of the whole beast. If that's not good for other people, an "expand all" button should be the quickest way back to see everything.
BTW: thanks for your great work.
