### ISSUE TITLE
A better handling of the text size would be ingenious

### ISSUE THREAD

**Issue by schittli** [b310-digital/teammapper#135]
Good mornng

**thank you very much for sharing your great work!**

I support small non-profit projects and I've tested TeamMapper for them.
I really like the tool, but because one can change the font size of the individual nodes individually by probably +/- 1 pixel, the diagrams look very quickly funny / choppy.

If one wants to make the diagram more professional and the font sizes more uniform, it becomes very tedious: When changing the font size, one does not see anywhere how big the font is exactly (e.g. "12px") and one has to estimate visually if it is approximately correct. And one must select each node individually to adjust the text size.

#### That's why I have these ideas to improve the handling of the font size:
- It would be great if one can see in the slider for the font size in a tooltip, which size one selects at the moment.
- It would be great if one could configure in the settings how big the step size is when changing the font size.
  I guess one can change the font size by +/- 1Px at the moment.
  Depending on how much detail my chart has, I would choose a larger increment.
- It would be even better if one could explicitly specify in the settings which font sizes are used, e.g. "8px, 12px, 15px, 17px".
  Then the slider would allow the user to choose only between these predefined sizes.

Thanks a lot, kind regards,
Thomas

**Comment by JannikStreek** [comment]
Hey @schittli, thank you for your kind words. I will look into this and get back to you if I have further questions or I can show you an update regarding this issue :)

**Comment by JannikStreek** [comment]
Hi @schittli , if you want you can try the linked pull request. I have added the following features:

- [x] Defaults for increment, min, max values for font sizes. These can be adjusted per server in the json file.
- [x] Settings for font increments, max, min sizes per map. These can be adjusted in the settings on the running app and are synced among all joined clients. So everyone uses the same (adjusted) settings.
- [x] I added hotkeys (ALT + -. ALT + .) as I realized none where given yet.

Feel free to try! Feedback welcome :)

**Comment by JannikStreek** [comment]
Merged a solution, for further improvements please open a new issue :)
