### ISSUE TITLE
new nodes require reload

### ISSUE THREAD

**Issue by retarepo** [b310-digital/teammapper#187]
Hello,

I just tried the app and really like the idea and how it looks, just one bug makes it very hard to use:
Each time I create a new node "by pressing +", the new node is shown, but not the text, which I write inside, nor any indicator, that am currently writing something inside. After refreshing the page it is fixed and I even see the text which I was prior typing in blindly. The next new node has the same problem. just editing existing nodes do not show this problem at any stage.

Does somebody has an idea where this stems from?

I am using
Firefox 112.0.2 on Ubuntu 20.04 with Gnome 3.36.8

Best regards

**Comment by JannikStreek** [comment]
Hi @retarepo,

thanks for the bug report. I just double checked this, happens also for me on Mac. I will get back to you when this is fixed!

Best regards
Jannik
