### ISSUE TITLE
Raspberry Pi 4 Setup

### ISSUE THREAD

**Issue by BloodshotPico** [b310-digital/teammapper#189]
Trying to set this up via a Raspberry Pi 4 but it seems like it's not built for arm64 but from what I can see it should work?

Not sure if that's 100% correct however, just wondering if I can get this to work and running on a Pi, I'm trying to do this with the docker compose method.

Thanks in advance,
~Blood

**Comment by JannikStreek** [comment]
Hey @BloodshotPico , thanks for raising this issue. You could try to build the image yourself:  e.g. `docker buildx build --platform linux/arm64 . `, have you tried that?

**Comment by BloodshotPico** [comment]
I've not tried this, sadly I don't know much in the way of docker to be able to do this. But thank for letting me know that it should be possible. :)

**Comment by JannikStreek** [comment]
@BloodshotPico i will double check, if I can adjust the GitHub action to also provide a pi image as default

**Comment by BloodshotPico** [comment]
@JannikStreek that would be lovely. Haven't gotten around to mess with the docker etc as much right now it's something I'm looking to learn though.

**Comment by JannikStreek** [comment]
@BloodshotPico can you try this image: `ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github`

it should include a raspberry optimized variant

**Comment by BloodshotPico** [comment]
Trying to build it gives me this error:
`docker build ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github
[+] Building 0.0s (0/0)
ERROR: unable to prepare context: path "ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github" not found`

**Comment by JannikStreek** [comment]
> Trying to build it gives me this error:
> 
> `docker build ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github [+] Building 0.0s (0/0) ERROR: unable to prepare context: path "ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github" not found`

you don't have to build it, just reference it in your docker compose file or pull it: `docker pull ghcr.io/b310-digital/teammapper:189-add-xbuild-to-github` depending on how you try to set it up. Its already built :) you  only need to download and start it

**Comment by BloodshotPico** [comment]
I'll have a play with this later today. :)

**Comment by JannikStreek** [comment]
its merged, closing this for now
