### ISSUE TITLE
Update Favicon to match the new logo

### ISSUE THREAD

**Issue by mariushosting** [b310-digital/teammapper#193]
It would be great to update the browser favicon to match the new logo.

**Comment by JannikStreek** [comment]
@mariushosting Hi, thanks for reporting, which browser are you using ? At least for me on safari und chrome it displays the correct ones.

**Comment by mariushosting** [comment]
> @mariushosting Hi, thanks for reporting, which browser are you using ? At least for me on safari und chrome it displays the correct ones.

Latest chrome Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by JannikStreek** [comment]
@mariushosting it works for me, same chrome version:

<img width="238" alt="Bildschirm­foto 2023-10-14 um 09 43 45" src="https://github.com/b310-digital/teammapper/assets/606519/45f3287e-e94e-49d4-8f9d-5bbe1759e6b6">

However, I did some cleanup, can you check within a private chrome tab if this branch is working ? [193-cleanup-resources](https://github.com/b310-digital/teammapper/pull/194)

**Comment by mariushosting** [comment]
> @mariushosting it works for me, same chrome version:
> 
> <img alt="Bildschirm­foto 2023-10-14 um 09 43 45" width="238" src="https://user-images.githubusercontent.com/606519/275163680-45f3287e-e94e-49d4-8f9d-5bbe1759e6b6.png">
> However, I did some cleanup, can you check within a private chrome tab if this branch is working ? [193-cleanup-resources](https://github.com/b310-digital/teammapper/pull/194)

Yes this branch works!

**Comment by JannikStreek** [comment]
perfect, then I will merge it and close this issue. thanks again for reporting.
