### ISSUE TITLE
Missing toast when trying to delete root node

### ISSUE THREAD

**Issue by sorenjohanson** [b310-digital/teammapper#303]
**Proposed feature**
Currently, there's an error being logged to the console whenever a user tries to delete the root node, but nothing happens otherwise. We should display a toast instead telling the user that the root node can't deleted.

**Comment by sorenjohanson** [comment]
Looking at this, it might make more sense to display an error toast in general when we call `Log.error()`, though not sure how useful most of these error messages are for end clients.

**Comment by JannikStreek** [comment]
I wouldn't call it in general. As you say, not every error does provide good information. I like the idea of a toast when the user tries to delete the root. 👍
