### ISSUE TITLE
Link icon disappears when reloading the page

### ISSUE THREAD

**Issue by sorenjohanson** [b310-digital/teammapper#380]
**Describe the bug**
When reloading the page, the link icon disappears but the actual link stays attached to the node. This makes it impossible to actually open the link, even though the icon in the toolbar still says "Remove a link"

**To Reproduce**
1. Add a link to any node
2. Reload the page
3. Watch the icon below the node disappear, even though the link is still attached to the node

**Expected behavior**
The `<text>` block should remain visible even when reloading a page so the link remains always accessible.

**Comment by JannikStreek** [comment]
I cant reproduce this on teammapper.org

**Comment by sorenjohanson** [comment]
> I cant reproduce this on teammapper.org

I'll see if I can reproduce this on main, but I assume not.

**Comment by sorenjohanson** [comment]
Was an error in #325 and not on main.
