### ISSUE TITLE
Fix warning: Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#454]
**Describe the bug**
Every time when a node is added, I see this warning in the console
```
draw.ts:89 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Task: Investigate why its there and preferably fix it as well.

**Comment by sorenjohanson** [comment]
Do we have any issues with scroll performance? This warning is only visible when setting logging levels to include verbose, and setting 'passive' on the event handler (that's been there forever) would only help scroll performance and nothing else.

**Comment by JannikStreek** [comment]
> Do we have any issues with scroll performance? This warning is only visible when setting logging levels to include verbose, and setting 'passive' on the event handler (that's been there forever) would only help scroll performance and nothing else.

the warning in the console can't be there forever, its the first time I actually saw it yesterday. also it appears with every node that is added and not with scrolling.

**Comment by sorenjohanson** [comment]
@JannikStreek This can't be changed, since we're intentionally preventing the default action (scrolling) in the `touchstart` event handler on mobile. Adding passive leads to the following error:

`draw.ts:94 Unable to preventDefault inside passive event listener invocation.`
