### ISSUE TITLE
Investigate log errors with WsExceptionsHandler undefined

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#574]
**Describe the bug**
Investigate causes of this bug, which is present since the undo/redo change (https://github.com/b310-digital/teammapper/commit/5609cdf9355ae3b7f7207c8772b994dfbd42b2e3). Unfortunately, there is not more in the logs. My best guess is an unhandled promise error that is not handled properly. I would suggest to double check the redo/undo pr and double check all promise returns.

Another hint: These are happening multiple times directly after each other, e.g. 7 times this error in the same second.

```
[Nest] 52 - 11/18/2024, 10:15:38 AM ERROR [WsExceptionsHandler] undefined
```

**Comment by JannikStreek** [comment]
Often I see this error before, but it happens several seconds before so I guess its not the same action, but belongs to the same session:

```
2024-11-18 11:10:21.092121790 +0100 CET [web-1] [Nest] 52 - 11/18/2024, 10:10:21 AM WARN [MapsService] Parent with id SOME_MAP_ID does not exist for node SOME_NODE_ID and map SOME_MAP_ID
```

**Comment by sorenjohanson** [comment]
We have a lot of places in the code where we simply return `Promise.reject()` without any error message. Maybe it's caused by that? I can get it to reproduce semi-reliably when I try very hard to break undo/redo.

**Comment by JannikStreek** [comment]
> We have a lot of places in the code where we simply return `Promise.reject()` without any error message. Maybe it's caused by that? I can get it to reproduce semi-reliably when I try very hard to break undo/redo.

I would have hoped that we can define a general error handler that catches exceptions at last resort. Just prompting undefined isn't really helpful currently. Maybe we can configure it properly? Also, if the rejects are expected, nothing should be raised at all. So maybe we are rejecting too often instead of resolving with a default value?
